hometuitionapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import url
from .views import *
from . import views
from .tokens import user_tokenizer

app_name = 'hometuitionapp'
urlpatterns = [
    # client side
    path('', HomeView.as_view(), name="home"),
    path("aboutus/", AboutusView.as_view(), name="aboutus"),
    path("contactus/", ContactusView.as_view(), name="contactus"),
    path('login/', LoginView.as_view(), name="login"),
    path('student/login/', StudentLoginView.as_view(), name="studentlogin"),
    path('student/register/', StudentRegisterView.as_view(), name="studentregister"),
    path('teacher/login/', TeacherLoginView.as_view(), name="teacherlogin"),
    path('teacher/register/',TeacherRegisterView.as_view(),
         name="teacherregister"),
    path('confirm-email/<str:user_id>/<str:token>/',
         views.ConfirmRegistrationView.as_view(), name='confirm_email'),
    path('confirm-email1/<str:user_id>/<str:token>/',
         views.ConfirmRegistration1View.as_view(), name='confirm_email1'),
    path('teacher/home/', TeacherHomeView.as_view(), name="teacherhome"),
    path('student/home/', StudentHomeView.as_view(), name="studenthome"),
    path('password_reset',views.password_reset_request, name="password_reset"),
    path('password_resett',views.password_reset_requestt, name="password_resett"),
    path('teacher/<int:pk>/profile/',
         TeacherProfileView.as_view(), name="teacherprofile"),
    path('teacher/<int:pk>/detail/',
         TeacherDetailView.as_view(), name="teacherdetail"),
    path('teacher/<int:pk>/update/',
         TeacherUpdateView.as_view(), name="teacherupdate"),
    path('teacher/<int:pk>/delete/',
         TeacherDeleteView.as_view(), name="teacherdelete"),
    path('student/<int:pk>/detail/',
         StudentDetailView.as_view(), name="studentdetail"),
    path('student/<int:pk>/update/',
         StudentUpdateView.as_view(), name="studentupdate"),
    path('student/<int:pk>/delete/',
         StudentDeleteView.as_view(), name="studentdelete"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('teacher/notification/create/', TeacherNotificationCreateView.as_view(), name="teachernotificationcreate"),
    path('teacher/hire/', AjaxTeacherHireView.as_view(), name="ajaxhireteacher"),
    # path('student/accept/', AjaxStudentAcceptView.as_view(), name="ajaxstudentaccept"),
    path('student/<int:pk>notification/update/', StudentNotificationUpdateView.as_view(), name="studentnotificationupdate"),
    path('teacher/notification/list/', TeacherNotificationListView.as_view(), name="teachernotificationlist"),
    path('student/notification/list/', StudentNotificationListView.as_view(), name="studentnotificationlist"),
    path('teacher/notification/<int:pk>/detail/',
         TeacherNotificationDetailView.as_view(), name="teachernotificationdetail"),
    path("ajax/hiring/accept/request/", AjaxHiringAcceptRequestView.as_view(), name="ajaxacceptrequest"),
    path("ajax/hiring/reject/request", AjaxHiringRejectRequestView.as_view(), name="ajaxrejectrequest"),
    path('payment/status/', PaymentStatusView.as_view(), name="paymentstatus"),


    # admin side
    path('system_admin/', AdminHomeView.as_view(), name="adminhome"),
    path('adminlogin/', AdminLoginView.as_view(), name="adminlogin"),
    path('system_admin/hometuitionsystem/<int:pk>/detail/',
         AdminHomeTuitionSystemDetailView.as_view(), name="adminsystemdetail"),
    path('system_admin/hometuitionsystem/<int:pk>/update/',
         AdminHomeTuitionSystemUpdateView.as_view(), name="adminsystemupdate"),
    path('system_admin/course/list/',
         AdminCourseListView.as_view(), name="admincourselist"),
    path('system_admin/course/create/',
         AdminCourseCreateView.as_view(), name="admincoursecreate"),
    path('system_admin/course/<int:pk>/update/',
         AdminCourseUpdateView.as_view(), name="admincourseupdate"),
    path('system_admin/course/<int:pk>/delete/',
         AdminCourseDeleteView.as_view(), name="admincoursedelete"),
    path('system_admin/subject/list/',
         AdminSubjectListView.as_view(), name="adminsubjectlist"),
    path('system_admin/hire/list/',
         AdminHireListView.as_view(), name="adminhirelist"),
    path('system_admin/subject/create/',
         AdminSubjectCreateView.as_view(), name="adminsubjectcreate"),
    path('system_admin/subject/<int:pk>/update/',
         AdminSubjectUpdateView.as_view(), name="adminsubjectupdate"),
    path('system_admin/subject/<int:pk>/delete/',
         AdminSubjectDeleteView.as_view(), name="adminsubjectdelete"),
    path('system_admin/student/list/',
         AdminStudentListView.as_view(), name="adminstudentlist"),

    path('system_admin/student/<int:pk>/detail/',
         AdminStudentDetailView.as_view(), name="adminstudentdetail"),

    path('system_admin/student/<int:pk>/update/',
         AdminStudentUpdateView.as_view(), name="adminstudentupdate"),
    path('system_admin/student/<int:pk>/delete/',
         AdminStudentDeleteView.as_view(), name="adminstudentdelete"),
    path('system_admin/teacher/list/',
         AdminTeacherListView.as_view(), name="adminteacherlist"),

    path('system_admin/teacher/<int:pk>/detail/',
         AdminTeacherDetailView.as_view(), name="adminteacherdetail"),

    path('system_admin/teacher/<int:pk>/update',
         AdminTeacherUpdateView.as_view(), name="adminteacherupdate"),
    path('system_admin/teacher/<int:pk>delete',
         AdminTeacherDeleteView.as_view(), name="adminteacherdelete"),

     path('system_admin/ajax/search/', 
     AdminAjaxTeacherSearchView.as_view(), name='adminajaxteachersearch'),
    path('adminlogout/', AdminLogoutView.as_view(), name="adminlogout"),

]

hometuitionproject/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin1/', admin.site.urls),
    path('', include("hometuitionapp.urls")),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="clienttemplates/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='clienttemplates/password_reset_complete.html'), name='password_reset_complete'),      



]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/clienttemplates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http:// {{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/clienttemplates/password_reset.html
{% extends "clienttemplates/base.html" %}
{% block content %}
<div class="container p-5">
  	 	<h2 class="font-weight-bold mt-3">Reset Password</h2>
		<hr>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
            {{ password_reset_form }}                    
            <button class="btn btn-primary" type="submit">Send email</button>
            	{% if messages %}
                	<div class="col-lg-3 color03">
                    	<ul class="messages">
                        	{% for message in messages %}
                            	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        	{% endfor %}
                    	</ul>
                	</div>
            	{% endif %}
        </form>
  	</div> 
{% endblock %}

templates/clienttemplates/payment.html
{% extends "clienttemplates/studentbase.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'clientstatic/css/login.css' %}" type="text/css" media="all">
{% block css %}
<style>
.payment {
    width: 100%;
}
</style>
{% endblock %}
{% block content %}
<div class="login-section">
<div class="flex-container">
<div class="flex-group">	
<h3>Payment Form</h3>
</div>
<form class="form-group" method="POST">
<!-- Cross Site Request Forgery refers to attempts to send request from an external site while pretending to be the origin application which is often use by attackers to execute malicious actions in the server.-->
<!-- Django protects against CSRF attacks by generating a CSRF token in the server -->
	
	
    <div class="flex-group mt-3" style="width: 100%;">
        Amount: <input type="text" name="" value="2000">
    </div>
    <br>
	<div class="flex-group">	
	<button class="btn btn-primary login-btn" type="submit" >Submit</button>
</div>
</form>
</div>
</div>

{% endblock %}

templates/clienttemplates/signup.html
{% extends "clienttemplates/base.html" %}
{% block content %}
<h4>Signup Form</h4>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	{{error}}
	<button>Signup</button>	
</form>
{% endblock %}

templates/clienttemplates/studenthome.html
{% extends "clienttemplates/studentbase.html" %}
{% load static %}
{% block content %}
<h1 style="text-align: center;">Teacher List</h1>
<a href="{% url 'hometuitionapp:studentnotificationlist' %}">Notification</a>
<a href="{% url 'hometuitionapp:paymentstatus' %}">Payment</a>

{% if messages %}
    	<div class="col-lg-3 color03">
        	<ul class="messages">
            	{% for message in messages %}
                	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            	{% endfor %}
        	</ul>
    	</div>
{% endif %}

<h1 style="text-align: center;" class=" mt-3 "> <a href="{% url 'hometuitionapp:studenthome' %}">Teacher List</a></h1>

<form method="GET" action="">
	<div class="container form-row my-2" style="margin-left: auto; margin-right: auto;">
		<div class="form-group col-6">
			<div class="input-group">
				<input class="form-control py-2 border border-dark rounded subject_val" type="search" name="subject" placeholder="Subject" />
			</div>
		</div>
		<div class="form-group col-5">
			<div class="input-group">
				<input class="form-control py-2 border border-dark rounded location_val" type="search" name="location" placeholder="Location" />
			</div>
		</div>   
		<div class="form-group col-1">
			<button type="submit" class="btn btn-primary" id="search_button">Search</button>
		</div>       
	</div>
</form>

<div class="row" id="ajaxsearch">
		<div class="col-md-12">
			<div class="container row mt-2 mb-2" style="margin-left: auto; margin-right: auto;">
				{% for teacher in teacher_list.object_list %}
				<div class="col-3 mt-3 mb-3" style="text-align: center;">
					<a href="{% url 'hometuitionapp:teacherprofile' teacher.pk %}"><img style=" max-width: 100%; " src="{{teacher.photo.url}}"/></a>
					<div class="mt-3 mb-3">
						<h4><a href="{% url 'hometuitionapp:teacherprofile' teacher.pk %}">{{teacher.name}}</a></h4>
						<p>Subject:{{teacher.subject}}</p>
						<p>Experience: {{teacher.experience}} </p>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
		<div class="col-md-12">
			<div class="container">
				<nav aria-label="...">
					<ul class="pagination">
						<li class="page-item {% if not prev_page_url %}disabled {% endif %}">
							<a class="page-link" href="{{ prev_page_url }}" tabindex="-1" aria-disabled="true">Previous</a>
						</li>
				
						{% for n in teacher_list.paginator.page_range %}
								{% if teacher_list.number == n %}
									<li class="page-item active" aria-current="page">
											<a class="page-link" href="?page={{ n }}"> {{ n }} <span class="sr-only">(current)</span></a>
									</li>
								
								{% elif n > teacher_list.number|add:-3 and n < teacher_list.number|add:3 %}
									<li class="page-item">
										<a class="page-link" href="?page={{ n }}"> {{ n }} </a>
									</li>
								{% endif %}
				
						{% endfor %}
						<li class="page-item {% if not next_page_url %}disabled {% endif %}">
							<a class="page-link" href="{{ next_page_url }}">Next</a>
						</li>
					</ul>
				  </nav>
			</div>
			
			
		</div>
	</div>


{% endblock %}

{% block js %}
<script>

	// search teacherlist using subject and location
	$('#search_button').on('click', function(e){
		e.preventDefault();
		alert("clicked");
		var subject = $('.subject_val').val();
		var location = $('.location_val').val();
		// alert("alert")
		if(subject == "" && location == ""){
			alert("Empty Fill")
		}
		else{
			$.ajax({
			url: "{% url 'hometuitionapp:adminajaxteachersearch' %}",
			data: {
				'subject': subject,
				'location': location,
			},
			success: function(data){
				// alert("success");
				$('#ajaxsearch').html(data)
			}
		});
		}
		
		
	});
</script>

{% endblock %}

templates/clienttemplates/studentnotificationcreate.html
{% extends "clienttemplates/studentbase.html" %}
{% block content %}
                <div class="container-fluid">
                    <div class="row">
                        <div class="outer-w3-agile col-xl mt-3 mr-xl-3">
                            <h4 class="tittle-w3-agileits mb-4">Confirmation Form</h4>
                            <form method="post">
                                {% csrf_token %}
                                <!-- {% for hire in hires %}
                                    <input type="hidden" name="{{form.teacher}}" value="{{hire.teacher}}">
                                    <input type="hidden" name="{{form.student}}" value="{{hire.student}}">
                                {% endfor %} -->
                                {{form.as_p}}
                                <button type="submit">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>

{% endblock %}

templates/clienttemplates/studentregister.html
{% extends "clienttemplates/base.html" %}
{% load static %}
{% block css %}
{% endblock %}
{% block content %}


<div class="contact-grids1 w3agile-6 registration">
	<h3>Registration Form </h3>

<form action="" enctype="multipart/form-data" method="post">
	{% csrf_token %}
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Username</label>
				{{form.username}}
				{{form.username.errors}}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Email</label>
				{{form.email}}
				{{form.email.errors}}
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Password</label>
				{{form.password}}
			</div>

			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Confirm Password</label>
				
				{{form.confirm_password}}
				
				{{form.confirm_password.errors}}

			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Name</label>
				{{form.name}}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Phone no</label>
				{{form.phone_no}}
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Address</label>
				{{form.address}}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Report Card</label>
				{{form.report_card}}
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Course</label>
				{{form.course}}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Subject</label>
				{{form.subject}}
			</div>
		</div>
		<!-- {%	for	field	in	form	%}
		<div>				
			{{	field.errors	}}		
		</div> 
		{%	endfor	%} -->
		<div class="row">
			<div class="col-md-12 form-group">
				<button type="submit" class="btn btn-primary fa-pull-right">Submit</button>
			</div>
			
		</div>
		
		
	</form>	
</div>
{% endblock %}

templates/clienttemplates/studentupdate.html
{% extends "clienttemplates/studentbase.html" %}
{% block content %}
<h4>Update Form</h4>
<form enctype="multipart/form-data" method="POST">
	{% csrf_token %}
	{{form.as_p}}
	{{error}}
	<button>Submit</button>	
</form>
{% endblock %}

templates/clienttemplates/teacherdelete.html
{% extends "clienttemplates/teacherbase.html" %}
{% block content %}
<div class="mt-3 mb-2">
    <h1>{{teacherdetail.name}}</h1>
    <img src="{{teacherdetail.photo.url}}"/>
    <p> Gender: {{teacherdetail.gender}}</p>
    <p>Phone_no: {{teacherdetail.phone_no}}</p>
    <p>Email:{{teacherdetail.email}}</p>
    <p>Address:{{teacherdetail.address}}</p>
    <p>Education:{{teacherdetail.education}}</p>
    <p>Experience:{{teacherdetail.experience}}</p>
    <p>CV:{{teacherdetail.cv}}</p>
    <p>Citizenship:{{teacherdetail.citizenship}}</p>
    <p>Course:{{teacherdetail.course}}</p>
    <p>Subject:{{teacherdetail.subject}}</p>
</div>
<div id="del" class="deleteAccount">
	<a href="{% url 'hometuitionapp:teacherdetail' request.user.teacher.id %}" class="close" title="Close">&times;</a>
	<form method="POST">
		{% csrf_token %}
		<div class="delete-form-container">
			<h3>Delete Account</h3>
			<p>Do you want to delete this account?</p>
			<div class="clearfix">
				<button type="submit" class="btn btn-danger deletebtn">Yes</button>
				<a href="{% url 'hometuitionapp:teacherdetail' request.user.teacher.id %}" class="btn btn-default cancelbtn">No</a>			
			</div>
		</div>
	</form>
</div>
	<!-- <div id="del" class="deleteAccount">
		<a href="{% url 'hometuitionapp:teacherdetail' request.user.teacher.id %}" class="close" title="Close">&times;</a>
		<form class="delete-form" method="POST">
		  {% csrf_token %}
		  <div class="delete-form-container">
			<h1>Delete Account</h1>
			<p>Are you sure you want to delete your account?</p>
	  
			<div class="clearfix">
			  <a href="{% url 'hometuitionapp:teacherdetail' request.user.teacher.id %}" type="button" class="btn btn-default cancelbtn" style="color:black;">Cancel</a>
			  <button type="button" class="btn btn-danger deletebtn">Delete</button>
			</div>
		  </div>
		</form>
	  </div> -->
{% endblock %}

templates/clienttemplates/teachernotificationlist.html
{% extends "clienttemplates/base.html" %}
{% load static %}
{% block content %}
<!-- {% for notification  in teachernotificationlist %}
<a href="{% url 'hometuitionapp:teachernotificationdetail' notification.pk %}"><li>{{notification.student}} hired {{notification.teacher}}</li></a>

                
{% endfor %} -->
    
<div class="container-fluid">
    <div class="row">
        <div class="outer-w3-agile col-xl">
            <div class="work-progres">
                <h4 class="tittle-w3-agileits mb-4">Notification</h4>
                <hr>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <tbody>
                            {% for notification  in teachernotificationlist %}
                            		<tr>
                            			<td>{{forloop.counter}}</td>
                            			<td><a href="{% url 'hometuitionapp:teachernotificationdetail' notification.pk %}" >{{notification.student}} hired {{notification.teacher}}</a></td>
                            		</tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/clienttemplates/teacherprofile.html
{% extends "clienttemplates/studentbase.html" %}
{% load static %}
    <!-- Font Awesome 5 link -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
{% block css %}
    <style>
        .checked {
            color: orange;
        }

        .my-btn {
            background-color: inherit !important;
            border: 0 !important;
            display: none;
        }
    </style>
{% endblock %}
{% block content %}
<h1 style="text-align: center;" class="mt-3">Teacher Profile</h1>
<div class="container mb-4">
    <h1>{{profile.name}}</h1>
    <!-- <h3>{{profile.name}}</h3> -->
    <img src="{{profile.photo.url}}"/>
    <div class="row"> 
        <div class="col-6 mt-3">
            <h4 class="mb-3">Description</h4>
            <hr>
            <div>
                <div>
                    <i class="{% if profile.averagerating >= 1 %}fas fa-star checked {% endif%} 
                        {% if profile.averagerating < 1 %}fas fa-star {% endif%}"></i>
                    <i class="{% if profile.averagerating >= 2 %}fas fa-star checked {% endif%}
                        {% if profile.averagerating < 2 %}fas fa-star {% endif%}"></i>
                    <i class="{% if profile.averagerating >= 3 %}fas fa-star checked {% endif%}
                        {% if profile.averagerating < 3 %}fas fa-star {% endif%}"></i>
                    <i class="{% if profile.averagerating >= 4 %}fas fa-star checked {% endif%}
                        {% if profile.averagerating < 4 %}fas fa-star {% endif%}"></i>
                    <i class="{% if profile.averagerating >= 5 %}fas fa-star checked {% endif%} 
                        {% if profile.averagerating < 5 %}fas fa-star {% endif%}"></i>
                    {{ profile.averagerating |stringformat:".2f" }}
                </div>
                <p> {{ profile.countrating }} Review(s) </p>
            </div>
            <p>Gender: {{profile.gender}}</p>
            <p>Phone_no: {{profile.phone_no}}</p>
            <p>Email:{{profile.email}}</p>
            <p>Address:{{profile.address}}</p>
            <p>Education:{{profile.education}}</p>
            <p>Experience:{{profile.experience}}</p>
            <!-- <p>CV:{{profile.cv}}</p>
            <p>Citizenship:{{profile.citizenship}}</p> -->
            <p>Course:{{profile.course}}</p>
            <p>Subject:{{profile.subject}}</p>
            <a class="hire_teacher btn btn-success">Hire</a>

        </div>    
        <div class="form-group col-6 mt-3">
            <h4 class="mb-3">Your Rating</h4>
            <hr>
            <form class="rate-form" action="" method="POST">
                {% csrf_token %}
                <input type="radio" name="rate" value="1" class="my-btn" id="first"></input><label id="one" class="fas fa-star checked" for="first"></label>
                <input type="radio" name="rate" value="2" class="my-btn" id="second"></input><label id="two" class="fas fa-star checked" for="second"></label>
                <input type="radio" name="rate" value="3" class="my-btn" id="third"></input><label id="three" class="fas fa-star" for="third"></label>
                <input type="radio" name="rate" value="4" class="my-btn" id="fourth"> </input><label id="four" class="fas fa-star" for="fourth"></label>
                <input type="radio" name="rate" value="5" class="my-btn" id="fifth"></input><label id="five" class="fas fa-star" for="fifth"></label>

                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
            <!-- Displaying message -->
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert" style="width: 100%; margin-left: auto; margin-right: auto; margin-top: 1rem;">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block js %}

<script type="text/javascript">
    $('.hire_teacher').on('click', function(e){
        e.preventDefault();
        var teacher_id = "{{profile.id}}"
        $.ajax({
            method: 'post',
            url: "{% url 'hometuitionapp:ajaxhireteacher' %}",
            data: {
                'teacher_id': teacher_id,
                'csrfmiddlewaretoken': '{{csrf_token}}',
            },
            success: function(data){
                if (data.message == "already"){
                    alert("Already Send request to this teacher.")
                }
                else {
                    alert("Teacher Hired Successfully.")
                }
            }
        })

    })
</script>
{% endblock %}

templates/clienttemplates/teacherregister.html
{% extends "clienttemplates/base.html" %}
{% load static %}
{% block css %}
{% endblock %}
{% block content %}

<div class="contact-grids1 w3agile-6 registration">

	<h3>Registration Form </h3>

<form action="" enctype="multipart/form-data" method="post">
	{% csrf_token %}
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Username</label>
				{{form.username}}
				{{form.username.errors}}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Email</label>
				{{form.email}}
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Password</label>
				{{form.password}}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Confirm Password</label>
				
				{{form.confirm_password}}
				
				{{form.confirm_password.errors}}

			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Name</label>
				{{form.name}}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Address</label>
				{{form.address}}
			</div>
			
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Phone no</label>
				{{form.phone_no}}
			</div>
			
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Photo</label>
				{{form.photo}}
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Gender</label>
				{{form.gender}}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Citizenship</label>
				{{form.citizenship}}
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Course</label>
				{% for item in form.course %}
                    <li><input type="checkbox", value="clicked", name="c{{item.id}}">{{item}}</li>
            	{% endfor %}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Subject</label>
				{% for item in form.subject %}
                    <li><input type="checkbox", value="clicked", name="c{{item.id}}">{{item}}</li>
            	{% endfor %}
			</div>
		</div>
		<!-- {%	for	field	in	form	%}
		<div>				
			{{	field.errors	}}		
		</div> 
		{%	endfor	%} -->
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Education</label>
				{{form.education}}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Experience</label>
				{{form.experience}}
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">CV</label>
				{{form.cv}}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Monthly Fee</label>
				{{form.monthly_fee}}
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Teaching Experience</label>
				{{form.teaching_experience}}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Teaching Location</label>
				{{form.can_teach_location}}
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Training License</label>
				{{form.traning_license}}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Availability</label>
				{{form.availability}}
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Reference Person Name</label>
				{{form.referenc_person}}
			</div>
			<div class="col-md-6 col-sm-6 form-group">
				<label class="col-form-label">Reference Person Contact</label>
				{{form.reference_person_contact_no}}
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 form-group">
				<button type="submit" class="btn btn-primary fa-pull-right">Submit</button>
			</div>
			
		</div>
</form>	
</div>
{% endblock %}