hometuitionapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import url
from .views import *
from . import views
from .tokens import user_tokenizer

app_name = 'hometuitionapp'
urlpatterns = [
    # client side
    path('', HomeView.as_view(), name="home"),
    path("aboutus/", AboutusView.as_view(), name="aboutus"),
    path("contactus/", ContactusView.as_view(), name="contactus"),
    path('login/', LoginView.as_view(), name="login"),
    path('student/login/', StudentLoginView.as_view(), name="studentlogin"),
    path('student/register/', StudentRegisterView.as_view(), name="studentregister"),
    path('teacher/login/', TeacherLoginView.as_view(), name="teacherlogin"),
    path('teacher/register/',TeacherRegisterView.as_view(),
         name="teacherregister"),
    path('confirm-email/<str:user_id>/<str:token>/',
         views.ConfirmRegistrationView.as_view(), name='confirm_email'),
    path('confirm-email1/<str:user_id>/<str:token>/',
         views.ConfirmRegistration1View.as_view(), name='confirm_email1'),
    path('teacher/home/', TeacherHomeView.as_view(), name="teacherhome"),
    path('student/home/', StudentHomeView.as_view(), name="studenthome"),
    path('password_reset',views.password_reset_request, name="password_reset"),
    path('password_resett',views.password_reset_requestt, name="password_resett"),
    path('teacher/<int:pk>/profile/',
         TeacherProfileView.as_view(), name="teacherprofile"),
    path('teacher/<int:pk>/detail/',
         TeacherDetailView.as_view(), name="teacherdetail"),
    path('teacher/<int:pk>/update/',
         TeacherUpdateView.as_view(), name="teacherupdate"),
    path('teacher/<int:pk>/delete/',
         TeacherDeleteView.as_view(), name="teacherdelete"),
    path('student/<int:pk>/detail/',
         StudentDetailView.as_view(), name="studentdetail"),
    path('student/<int:pk>/update/',
         StudentUpdateView.as_view(), name="studentupdate"),
    path('student/<int:pk>/delete/',
         StudentDeleteView.as_view(), name="studentdelete"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('teacher/notification/create/', TeacherNotificationCreateView.as_view(), name="teachernotificationcreate"),
    path('teacher/hire/', AjaxTeacherHireView.as_view(), name="ajaxhireteacher"),
    # path('student/accept/', AjaxStudentAcceptView.as_view(), name="ajaxstudentaccept"),
    path('student/<int:pk>notification/update/', StudentNotificationUpdateView.as_view(), name="studentnotificationupdate"),
    path('teacher/notification/list/', TeacherNotificationListView.as_view(), name="teachernotificationlist"),
    path('student/notification/list/', StudentNotificationListView.as_view(), name="studentnotificationlist"),
    path('teacher/notification/<int:pk>/detail/',
         TeacherNotificationDetailView.as_view(), name="teachernotificationdetail"),
    path("ajax/hiring/accept/request/", AjaxHiringAcceptRequestView.as_view(), name="ajaxacceptrequest"),
    path("ajax/hiring/reject/request", AjaxHiringRejectRequestView.as_view(), name="ajaxrejectrequest"),
    path('payment/status/', PaymentStatusView.as_view(), name="paymentstatus"),


    # admin side
    path('system_admin/', AdminHomeView.as_view(), name="adminhome"),
    path('adminlogin/', AdminLoginView.as_view(), name="adminlogin"),
    path('system_admin/hometuitionsystem/<int:pk>/detail/',
         AdminHomeTuitionSystemDetailView.as_view(), name="adminsystemdetail"),
    path('system_admin/hometuitionsystem/<int:pk>/update/',
         AdminHomeTuitionSystemUpdateView.as_view(), name="adminsystemupdate"),
    path('system_admin/course/list/',
         AdminCourseListView.as_view(), name="admincourselist"),
    path('system_admin/course/create/',
         AdminCourseCreateView.as_view(), name="admincoursecreate"),
    path('system_admin/course/<int:pk>/update/',
         AdminCourseUpdateView.as_view(), name="admincourseupdate"),
    path('system_admin/course/<int:pk>/delete/',
         AdminCourseDeleteView.as_view(), name="admincoursedelete"),
    path('system_admin/subject/list/',
         AdminSubjectListView.as_view(), name="adminsubjectlist"),
    path('system_admin/hire/list/',
         AdminHireListView.as_view(), name="adminhirelist"),
    path('system_admin/subject/create/',
         AdminSubjectCreateView.as_view(), name="adminsubjectcreate"),
    path('system_admin/subject/<int:pk>/update/',
         AdminSubjectUpdateView.as_view(), name="adminsubjectupdate"),
    path('system_admin/subject/<int:pk>/delete/',
         AdminSubjectDeleteView.as_view(), name="adminsubjectdelete"),
    path('system_admin/student/list/',
         AdminStudentListView.as_view(), name="adminstudentlist"),

    path('system_admin/student/<int:pk>/detail/',
         AdminStudentDetailView.as_view(), name="adminstudentdetail"),

    path('system_admin/student/<int:pk>/update/',
         AdminStudentUpdateView.as_view(), name="adminstudentupdate"),
    path('system_admin/student/<int:pk>/delete/',
         AdminStudentDeleteView.as_view(), name="adminstudentdelete"),
    path('system_admin/teacher/list/',
         AdminTeacherListView.as_view(), name="adminteacherlist"),

    path('system_admin/teacher/<int:pk>/detail/',
         AdminTeacherDetailView.as_view(), name="adminteacherdetail"),

    path('system_admin/teacher/<int:pk>/update',
         AdminTeacherUpdateView.as_view(), name="adminteacherupdate"),
    path('system_admin/teacher/<int:pk>delete',
         AdminTeacherDeleteView.as_view(), name="adminteacherdelete"),

     path('system_admin/ajax/search/', 
     AdminAjaxTeacherSearchView.as_view(), name='adminajaxteachersearch'),
    path('adminlogout/', AdminLogoutView.as_view(), name="adminlogout"),

]

hometuitionproject/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin1/', admin.site.urls),
    path('', include("hometuitionapp.urls")),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="clienttemplates/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='clienttemplates/password_reset_complete.html'), name='password_reset_complete'),      



]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admintemplates/admincoursecreate.html
{% extends "admintemplates/base.html" %}
{% block content %}
<!--// Inline Form -->
                <div class="container-fluid">
                    <div class="row">
                        <!-- Forms-1 -->
                        <div class="outer-w3-agile col-xl mt-3 mr-xl-3">
                            <h4 class="tittle-w3-agileits mb-4">Course Create Form</h4>
                            <form method="post">
                                {% csrf_token %}
                                {{form.as_p}}
                                <button>Submit data</button>
                            </form>
                        </div>
                    </div>
                </div>

{% endblock %}

templates/admintemplates/admincoursedelete.html
{% extends "admintemplates/base.html" %}
{% block content %}
<!--// Inline Form -->
                <div class="container-fluid">
                    <div class="row">
                        <!-- Forms-1 -->
                        <div class="outer-w3-agile col-xl mt-3 mr-xl-3">
                            <h4 class="tittle-w3-agileits mb-4">Delete Form</h4>
                            <form method="post">
                            	{% csrf_token %}
                            	<h4>Do you want to delete this?</h4>
                            	<button>yes</button>
                            </form>
                        </div>
                    </div>
                </div>           
{% endblock %}

templates/admintemplates/admincourseupdate.html
{% extends "admintemplates/base.html" %}
{% block content %}
<!--// Inline Form -->
                <div class="container-fluid">
                    <div class="row">
                        <!-- Forms-1 -->
                        <div class="outer-w3-agile col-xl mt-3 mr-xl-3">
                            <h4 class="tittle-w3-agileits mb-4">Course Form</h4>
                            <form enctype="multipart/form-data" method="post">
                            	{% csrf_token %}
                            	{{form.as_p}}
                            	<button>Submit data</button>
                            </form>
                        </div>
                    </div>
                </div>

{% endblock %}

templates/admintemplates/adminhirelist.html
{% extends "admintemplates/base.html" %}
{% load static %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <!-- Stats -->
        <div class="outer-w3-agile col-xl">
            <div class="work-progres">
                <h4 class="tittle-w3-agileits mb-4">Hire List</h4>
                <hr>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Teacher</th>
                                <th>Student</th>
                                <th>Created</th>
                                <th>Status</th>

                                <!-- <th>Status</th>  -->
                                <!-- <th>Action</th> -->
                            </tr>
                        </thead>
                        <tbody>
                            {% for hire in hirelist %}
                            		<tr>
                            			<td>{{forloop.counter}}</td>
                                        <td>{{hire.teacher}}</td>
                            			<td>{{hire.student}}</td>
                                        <td>{{hire.hire_date}}</td>
                            			<td>{{hire.accept}}</td>
                            			
                            		</tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/admintemplates/adminhome.html
{% extends "admintemplates/base.html" %}
{% load static %}
{% block content %}
            <div class="container-fluid">
                <div class="row">
                    <!-- Stats -->
                    <div class="outer-w3-agile col-xl">
                        <div class="stat-grid p-3 d-flex align-items-center justify-content-between bg-primary">
                            <div class="s-l">
                                <a href="{% url 'hometuitionapp:adminteacherlist' %}">
                                    <h5>Teacher</h5>
                                    <p class="paragraph-agileits-w3layouts text-white">Total Teachers</p>
                                </a>
                            </div>
                            <div class="s-r">
                                <h6>{{ teacher_list }}
                                    <!-- <i class="far fa-edit"></i> -->
                                </h6>
                            </div>
                        </div>
                        <div class="stat-grid p-3 mt-3 d-flex align-items-center justify-content-between bg-success">
                            <div class="s-l">
                                <a href=" {% url 'hometuitionapp:adminstudentlist' %} ">
                                    <h5>Students</h5>
                                    <p class="paragraph-agileits-w3layouts">Total Students</p>
                                </a>
                            </div>
                            <div class="s-r">
                                <h6>{{ student_list }}
                                    <!-- <i class="far fa-smile"></i> -->
                                </h6>
                            </div>
                        </div>
                        <div class="stat-grid p-3 mt-3 d-flex align-items-center justify-content-between bg-danger">
                            <div class="s-l">
                                <a href="{% url 'hometuitionapp:admincourselist' %}">
                                    <h5>Course</h5>
                                    <p class="paragraph-agileits-w3layouts">Total Courses</p>
                                </a>
                            </div>
                            <div class="s-r">
                                <h6>{{ course_list }}
                                    <!-- <i class="fas fa-tasks"></i> -->
                                </h6>
                            </div>
                        </div>
                        <!-- <div class="stat-grid p-3 mt-3 d-flex align-items-center justify-content-between bg-warning">
                            <div class="s-l">
                                <h5>Employees</h5>
                                <p class="paragraph-agileits-w3layouts">Lorem Ipsum</p>
                            </div>
                            <div class="s-r">
                                <h6>190
                                    <i class="fas fa-users"></i>
                                </h6>
                            </div>
                        </div> -->
                    </div>
                    <!--// Stats -->
                    <!-- Pie-chart -->
                    <!-- <div class="outer-w3-agile col-xl ml-xl-3 mt-xl-0 mt-3">
                        <h4 class="tittle-w3-agileits mb-4">Pie Chart</h4>
                        <div id="chartdiv"></div>
                    </div> -->
                    <!--// Pie-chart -->
                </div>
            </div>
            <!-- Simple-chart -->
            <!-- <div class="outer-w3-agile mt-3">
                <h4 class="tittle-w3-agileits mb-4">Graph</h4>
                <div id="Hybridgraph" class="simple-chart1">
                </div>
            </div> -->
            <!--// Simple-chart -->

            <!--// Bar-Chart -->
            <!-- <div class="outer-w3-agile mt-3">
                <h4 class="tittle-w3-agileits mb-4">Bar Chart</h4>
                <div id="chart-1"></div>
            </div> -->
            <!--// Bar-Chart -->

            <!--// three-grids -->
            <!-- <div class="container-fluid">
                <div class="row"> -->
                    <!-- Calender -->
                    <!-- <div class="outer-w3-agile col-xl mt-3">
                        <h4 class="tittle-w3-agileits mb-4">Multi range Calender</h4>
                        <div class="multi-select-calender"></div>
                        <div class="box"></div>
                    </div> -->
                    <!--// Calender -->
                    <!-- Profile -->
                    <!-- <div class="outer-w3-agile col-xl mt-3 mx-xl-3 p-xl-0 px-md-5">
                        <div class="header">
                            <div class="text">
                                <img src="{% static 'adminstatic/images/profile.jpg' %}" class="img-fluid rounded-circle" alt="Responsive image">
                                <h2>Matthew Scott</h2>
                                <a href="mailto:info@example.com">
                                    <p>@Lorem ipsum</p>
                                </a>
                            </div>
                        </div>
                        <div class="container-flud">
                            <div class="followers row">
                                <div class="f-left col">
                                    <a href="#">
                                        <i class="far fa-comments"></i>
                                    </a>
                                </div>
                                <div class="f-left col border-left border-right">
                                    <a href="#">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                </div>
                                <div class="f-left col">
                                    <a href="#">
                                        <i class="far fa-heart"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <ul class="prof-widgt-content">
                            <li class="menu">
                                <ul>
                                    <li class="button">
                                        <a href="#">
                                            <i class="fas fa-envelope"></i> Messages
                                            <span>13</span>
                                        </a>
                                    </li>
                                    <li class="dropdown">
                                        <ul class="icon-navigation">
                                            <li>
                                                <a href="#">Inbox
                                                    <span class="float-right">[09]</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#">Outbox
                                                    <span class="float-right">[01]</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#">Sent messages
                                                    <span class="float-right">[03]</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="menu">
                                <ul>
                                    <li class="button">
                                        <a href="#">
                                            <i class="fas fa-user"></i> Profile</a>
                                    </li>
                                    <li class="dropdown">
                                        <ul class="icon-navigation">
                                            <li>
                                                <a href="#">Change your pic</a>
                                            </li>
                                            <li>
                                                <a href="#">Change your username</a>
                                            </li>
                                            <li>
                                                <a href="#">About us</a>
                                            </li>
                                            <li>
                                                <a href="#">Contact me</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div> -->
                    <!--// Profile -->
                    <!-- Browser stats -->
                    <!-- <div class="outer-w3-agile col-xl mt-3">
                        <h4 class="tittle-w3-agileits mb-4">Browser Stats</h4>
                        <div class="stats-info stats-body">
                            <ul class="list-unstyled">
                                <li class="pb-3">GoogleChrome
                                    <span class="float-right">85%</span>
                                    <div class="progress progress-striped active progress-right">
                                        <div class="bar green" style="width:85%;"></div>
                                    </div>
                                </li>
                                <li class="py-md-4 py-3">Firefox
                                    <span class="float-right">35%</span>
                                    <div class="progress progress-striped active progress-right">
                                        <div class="bar yellow" style="width:35%;"></div>
                                    </div>
                                </li>
                                <li class="py-md-4 py-3">Internet Explorer
                                    <span class="float-right">78%</span>
                                    <div class="progress progress-striped active progress-right">
                                        <div class="bar red" style="width:78%;"></div>
                                    </div>
                                </li>
                                <li class="py-md-4 py-3">Safari
                                    <span class="float-right">50%</span>
                                    <div class="progress progress-striped active progress-right">
                                        <div class="bar blue" style="width:50%;"></div>
                                    </div>
                                </li>
                                <li class="py-md-4 py-3">Opera
                                    <span class="float-right">80%</span>
                                    <div class="progress progress-striped active progress-right">
                                        <div class="bar light-blue" style="width:80%;"></div>
                                    </div>
                                </li>
                                <li class="last py-md-4 py-3">Others
                                    <span class="float-right">60%</span>
                                    <div class="progress progress-striped active progress-right">
                                        <div class="bar orange" style="width:60%;"></div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div> -->
                    <!--// Browser stats -->
                <!-- </div>
            </div> -->
            <!--// Three-grids -->
            <!-- Countdown -->
            <!-- <div class="outer-w3-agile mt-3 outer-w3-agile-bg">
                <h4 class="tittle-w3-agileits mb-4 text-white">Countdown Timer</h4>
                <div class="simply-countdown-custom" id="simply-countdown-custom"></div>
            </div> -->
            <!--// Countdown -->
{% endblock %}

templates/admintemplates/adminlogin.html
{% load static %}
	<link rel="stylesheet" href="{% static 'adminstatic/css/login.css' %}">
	<!-- Bootstrap Css -->
	<link href="{% static 'adminstatic/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
	<!-- Bootstrap Css -->
	<!-- Fontawesome Css -->
	<link href="{% static 'adminstatic/css/fontawesome-all.css' %}" rel="stylesheet">
{% block content %} 
<div class="login-section">
	<div class="flex-container">
	<div class="flex-group">	
	<h3>Admin Login </h3>
	</div>
	<form class="form-group" method="POST">
	<!-- Cross Site Request Forgery refers to attempts to send request from an external site while pretending to be the origin application which is often use by attackers to execute malicious actions in the server.-->
	<!-- Django protects against CSRF attacks by generating a CSRF token in the server -->
		{% csrf_token %}
		<div class="flex-group">
		{{form.as_p}}
		</div>
		{% if error %}
		<div class="alert alert-danger alert-dismissible fade show mt-2 flex-group">
			{{error}}
			<button type="button" class="close" data-dismiss="alert">&times;</button>
		</div>
		{% endif %}
		<div class="flex-group mt-3">	
			<button type="submit" class="btn btn-primary">Login</button>
		</div>
	</form>
	</div>
	</div>
{% endblock %}
<!-- Js for bootstrap working-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'adminstatic/js/bootstrap.min.js' %}"></script>

templates/admintemplates/adminstudentlist.html
{% extends "admintemplates/base.html" %}
{% load static %}
{% block content %}

<!-- main-heading -->
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Widgets</h2> -->
<!--// main-heading -->

<div class="container-fluid">
    <div class="row">
        <div class="outer-w3-agile col-xl">
            <div class="work-progres">
                <h4 class="tittle-w3-agileits mb-4">Student List</h4>
                <hr>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Created</th>
                                <th>Status</th> 
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for student in studentlist %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td><a href="{% url 'hometuitionapp:adminstudentdetail' student.pk %}">{{student.name}}</a></td>
                                        <td>{{student.created_at}}</td>
                                        <td>{% if student.active %}active{% else %}inactive{% endif %}</td>
                                        <td><a href="{% url 'hometuitionapp:adminstudentupdate' student.pk %}" class="btn btn-primary btn-sm">Update</a>
                                        <a href="{% url 'hometuitionapp:adminstudentdelete' student.pk %}" class="btn btn-danger btn-sm">Delete</a></td>
                                    </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/admintemplates/adminsubjectdelete.html
{% extends "admintemplates/base.html" %}
{% block content %}
<!--// Inline Form -->
                <div class="container-fluid">
                    <div class="row">
                        <!-- Forms-1 -->
                        <div class="outer-w3-agile col-xl mt-3 mr-xl-3">
                            <h4 class="tittle-w3-agileits mb-4">Delete Form</h4>
                            <form method="post">
                            	{% csrf_token %}
                            	<h4>Do you want to delete this?</h4>
                            	<button>yes</button>
                            </form>
                        </div>
                    </div>
                </div>           
{% endblock %}

templates/admintemplates/adminsubjectlist.html
{% extends "admintemplates/base.html" %}
{% load static %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <!-- Stats -->
        <div class="outer-w3-agile col-xl">
            <div class="work-progres">
                <h4 class="tittle-w3-agileits mb-4">Subject List</h4>
                <hr>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Created</th>
                                <th>Status</th> 
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for subject in subjectlist %}
                            		<tr>
                            			<td>{{forloop.counter}}</td>
                            			<td>{{subject.name}}</td>
                            			<td>{{subject.created_at}}</td>
                            			<td>{% if subject.active %}active{% else %}inactive{% endif %}</td>
                            			<td><a href="{% url 'hometuitionapp:adminsubjectupdate' subject.pk %}" class="btn btn-primary btn-sm">Update</a>
                            			<a href="{% url 'hometuitionapp:adminsubjectdelete' subject.pk %}" class="btn btn-danger btn-sm">Delete</a></td>
                            		</tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/admintemplates/adminsubjectupdate.html
{% extends "admintemplates/base.html" %}
{% load static %}
{% block content %}
<h4>Subject Update Form</h4>
<!-- enctype='multipart/form-data is an encoding type that allows files to be sent through a POST -->
<form enctype="multipart/form-data" method="post">
	{% csrf_token %}
	{{form.as_p}}
	<button>Submit data</button>
</form>
{% endblock %}

templates/admintemplates/adminteacherlist.html
{% extends "admintemplates/base.html" %}
{% load static %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <!-- Stats -->
        <div class="outer-w3-agile col-xl">
            <div class="work-progres">
                <h4 class="tittle-w3-agileits mb-4">Teacher List</h4>
                <hr>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Created</th>
                                <th>Status</th> 
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for teacher in teacherlist %}
                        	<tr>
                        		<td>{{forloop.counter}}</td>
                                <td><a href="{% url 'hometuitionapp:adminteacherdetail' teacher.pk %}">{{teacher.name}}</a></td>
                        		<td>{{teacher.created_at}}</td>
                        		<td>{% if teacher.active %}active{% else %}inactive{% endif %}</td>
                        		<td><a href="{% url 'hometuitionapp:adminteacherupdate' teacher.pk %}" class="btn btn-primary btn-xs">Update</a>
                            		<a href="{% url 'hometuitionapp:adminteacherdelete' teacher.pk %}" class="btn btn-danger btn-xs">Delete</a>
                            	</td>
                        	</tr>
                        	{% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}